---
name: positivesuite
description: Application to manage favorite people in Positive Planet
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  firebase_auth: ^1.4.1
  flutter_svg: ^0.22.0
  responsive_grid: ^2.0.0
  google_sign_in: ^5.0.4
  font_awesome_flutter: ^9.1.0
  firebase_storage: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/backgrounds/
  - assets/icons/
